<?php 

require_once "../assets/assets.php";

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>

    <style>
        

.table-bordered.card {
	border: 0 !important;
}
.card thead {
	display: none;
}

.card tbody tr {
	float: left;
	width: 25em;
	margin: 0.5em;
	border: 1px solid #bfbfbf;
	border-radius: 0.5em;
	background-color: transparent !important;
	box-shadow: 0.25rem 0.25rem 0.5rem rgba(0, 0, 0, 0.25);
}
.card tbody tr td {
	display: block;
	border: 0;
}

p {
	text-align: center;
	color: limegreen;
	font-size: 1.5em;
	font-weight: bold;
	text-shadow: 1px 1px 2px #000;
	margin-bottom: 1.2em;
}
    </style>

<title>News</title>

<script>
$(document).ready(function() {
    $('#cardTable').DataTable({
        ajax: {
            url: '../grade/method.php',
            dataSrc: 'data' // Assuming your data is in a property named 'data'
        },
        columns: [
            { data: 'nrp' },
            { data: 'name' },
            { data: 'course_name' },
            { data: 'grade' }
        ],
        // Customizing the appearance of the cards
        drawCallback: function(settings) {
            var table = $('#cardTable').DataTable();
            var data = table.rows().data();

            // Clear the table body
            $('#cardTable tbody').empty();

            // Generate card elements and append them to the table body
            data.each(function(value, index) {
                var cardHtml = '<div class="card">';
                cardHtml += '<div class="card-body">';
                cardHtml += '<h5 class="card-title">' + value.nrp + '</h5>';
                cardHtml += '<p class="card-text">Name: ' + value.name + '</p>';
                cardHtml += '<p class="card-text">course: ' + value.course_name + '</p>';
                cardHtml += '<p class="card-text">Grade: ' + value.grade + '</p>';
                cardHtml += '</div>';
                cardHtml += '</div>';

                $('#cardTable tbody').append('<tr><td>' + cardHtml + '</td></tr>');
            });
        }
    });
});


window.addEventListener('DOMContentLoaded', event => {

// Toggle the side navigation
const sidebarToggle = document.body.querySelector('#sidebarToggle');
if (sidebarToggle) {
// Uncomment Below to persist sidebar toggle between refreshes
// if (localStorage.getItem('sb|sidebar-toggle') === 'true') {
//     document.body.classList.toggle('sb-sidenav-toggled');
// }
sidebarToggle.addEventListener('click', event => {
    event.preventDefault();
    document.body.classList.toggle('sb-sidenav-toggled');
    localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
});
}

});


</script>
</head>

<body>
<table id="cardTable" class="display">
    <thead>
        <tr>
            <th>NRP</th>
            <th>NAME</th>
            <th>COURSE</th>
            <th>GRADE</th>
        </tr>
    </thead>
    <tbody>
        <!-- Table body content will be dynamically generated by DataTables -->
    </tbody>
</table>


<!-- <p style="padding-bottom: 30px;"></p> -->


    
</div>

</body>
</html>